version: '3.9'

services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

  auth-service:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/auth_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      MINIO_ENDPOINT: http://minio:9000
      MINIO_SECRET_KEY: minioadmin
      MINIO_ACCESS_KEY: minioadmin
